# -*- coding: utf-8 -*-
"""B19_E22CSEU0557_RameshwariVadhvani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m95oONsHWzrUSNN7OE3ha_gxz8AgCeYv
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('/content/drive/MyDrive/Lena_Image.png')

resized_linear = cv2.resize(image, (300, 300), interpolation=cv2.INTER_LINEAR)
resized_nearest = cv2.resize(image, (300, 300), interpolation=cv2.INTER_NEAREST)
resized_polynomial = cv2.resize(image, (300, 300), interpolation=cv2.INTER_CUBIC)

# Display the resized images
plt.subplot(131), plt.imshow(cv2.cvtColor(resized_linear, cv2.COLOR_BGR2RGB)), plt.title('Linear')
plt.subplot(132), plt.imshow(cv2.cvtColor(resized_nearest, cv2.COLOR_BGR2RGB)), plt.title('Nearest Neighbors')
plt.subplot(133), plt.imshow(cv2.cvtColor(resized_polynomial, cv2.COLOR_BGR2RGB)), plt.title('Polynomial')
plt.show()

# Image Blurring
box_blur = cv2.blur(image, (5, 5))
gaussian_blur = cv2.GaussianBlur(image, (5, 5), 0)
adaptive_blur = cv2.bilateralFilter(image, 9, 75, 75)

plt.subplot(131), plt.imshow(cv2.cvtColor(box_blur, cv2.COLOR_BGR2RGB)), plt.title('Box Blurring')
plt.subplot(132), plt.imshow(cv2.cvtColor(gaussian_blur, cv2.COLOR_BGR2RGB)), plt.title('Gaussian Blurring')
plt.subplot(133), plt.imshow(cv2.cvtColor(adaptive_blur, cv2.COLOR_BGR2RGB)), plt.title('Adaptive Blurring')
plt.show()